### ISSUE TITLE
Successfully building Examples requires Testing to be built for VTK

### ISSUE THREAD

**Issue by gbivins** [lorensen/VTKWikiExamples#1]
I tried building the examples provided here from the command line (ie ccmake)  and it failed because my VTK wasn't built with Testing enabled. Seems like I should have the option to build the tests for the examples separately similar to the main VTK build. It would be even nicer if CMake for the examples could detect if testing had been built for the main VTK build and set itself up accordingly.
Also,some of the examples seem to erroneously include vtkTesting/TestingUtilities headers even though there isn't a reference to them in the cxx. Cxx/Visualization/StreamLines.cxx for example.

**Comment by ajpmaclean** [comment]
Just had a quick look at the example on the web page. It looks as #include
<vtkTestUtilities.h> was a leftover from the original test. It should be
safe to remove it or comment it out. You should be able to modify the code
by changing the example on the web page. If not I'll do it.

Are there any more examples that are causing you problems?

Andrew Maclean

**Comment by ajpmaclean** [comment]
Also #include <vtkTesting.h> could go too.

Andrew Maclean

**Comment by lorensen** [comment]
You are correct that VTK must be built with testing if you build all of the
wiki examples.
I'll take a look at fixing that, but it will take a bit of time.

Bill

**Comment by gbivins** [comment]
Here's a link to the Dockerfile that shows the files I had to basically ignore to successfully build without testing.
https://bitbucket.org/gbivins/vtk-docker/annotate/bdd5c0b41ff6dbaed87edca5b14593da995e0158/vtk-examples/Dockerfile?at=master#Dockerfile-38
I haven't had a chance to look more closely at the files to see if the testing/testutilities were actually needed in each of them.
I'd be willing to do the CMake mods with some guidance...My CMake is rather rusty and it'd be "moonlighting" so it'd probably take me some time as well.

**Comment by lorensen** [comment]
I have updated all of the CMakeLists.txt files to work with or without
testing. I also removed unneeded vtkTesting.h includes from some examples.
The examples that require vtkTesting now reognize that and will not be
built if testing is off.

NOTE: You will have to wait until the nightly wiki scrapping completes
before testing. Late tomorrow would be a good time.

Thanks for reporting this issue.

Bill

On Mon, Aug 31, 2015 at 12:03 PM, TheGbiv notifications@github.com wrote:

> Here's a link to the Dockerfile that shows the files I had to basically
> ignore to successfully build without testing.
> 
> https://bitbucket.org/gbivins/vtk-docker/annotate/bdd5c0b41ff6dbaed87edca5b14593da995e0158/vtk-examples/Dockerfile?at=master#Dockerfile-38
> I haven't had a chance to look more closely at the files to see if the
> testing/testutilities were actually needed in each of them.
> I'd be willing to do the CMake mods with some guidance...My CMake is
> rather rusty and it'd be "moonlighting" so it'd probably take me some time
> as well.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lorensen/VTKWikiExamples/issues/1#issuecomment-136415746
> .

## 

Unpaid intern in BillsBasement at noware dot com

**Comment by gbivins** [comment]
Nice! I guess your scale for "a bit of time" is much smaller than mine!
I'll give it a shot tomorrow.

**Comment by lorensen** [comment]
I'm retired... Too hot today to play golf or cut the lawn...

On Mon, Aug 31, 2015 at 3:52 PM, TheGbiv notifications@github.com wrote:

> Nice! I guess your scale for "a bit of time" is much smaller than mine!
> I'll give it a shot tomorrow.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lorensen/VTKWikiExamples/issues/1#issuecomment-136481468
> .

## 

Unpaid intern in BillsBasement at noware dot com

**Comment by lorensen** [comment]
You should be able to build the examples without editing or removing files.

Let me know if it works for you.

Bill

On Mon, Aug 31, 2015 at 3:54 PM, Bill Lorensen bill.lorensen@gmail.com
wrote:

> I'm retired... Too hot today to play golf or cut the lawn...
> 
> On Mon, Aug 31, 2015 at 3:52 PM, TheGbiv notifications@github.com wrote:
> 
> > Nice! I guess your scale for "a bit of time" is much smaller than mine!
> > I'll give it a shot tomorrow.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/lorensen/VTKWikiExamples/issues/1#issuecomment-136481468
> > .
> 
> ## 
> 
> Unpaid intern in BillsBasement at noware dot com

## 

Unpaid intern in BillsBasement at noware dot com

**Comment by gbivins** [comment]
My Dockerfile does a wget on this guy https://github.com/lorensen/VTKWikiExamples/archive/master.zip
and it seems to have not packed the updated StreamLines.cxx...not sure what's up with that but everything else worked as expected. I also noted that during the CMake/ninja build that it reported it was ignoring some files because BUILD_TEST was off so I think it's good to go. I imaging if I changed my Dockerfile to just clone the git repo it would work fine as well ... ¯_(ツ)_/¯

**Comment by lorensen** [comment]
I had forgotten to remove a #include <vtkTesting.h> from StreamLines.
SHould be Ok tomorrow.

On Wed, Sep 2, 2015 at 10:51 PM, TheGbiv notifications@github.com wrote:

> Closed #1 https://github.com/lorensen/VTKWikiExamples/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lorensen/VTKWikiExamples/issues/1#event-399634641.

## 

Unpaid intern in BillsBasement at noware dot com
